### ISSUE TITLE
example?

### ISSUE THREAD

**Issue by arendej** [thestormforge/konjure#6]
Please provide a use-case and example in your frontpage readme, otherwise Kustomize seems to already do this, no?

**Comment by jgustie** [comment]
Sorry for missing this, we haven't required many changes since the Konjure 0.3.0 release so I haven't really been on the GitHub page. I updated the README with some additional notes and a while back I also started a more [narrative example](https://github.com/thestormforge/konjure/blob/2a631909d06d0f88ec57c41392696caa0770e70e/ultimate-list-of-resources.yaml) (but the jury is still out on how useful it is, so it hasn't been merged).

Kustomize and Konjure are similar in some ways and different in others: Konjure actually started as a collection of Kustomize execution plugins (in 0.1.x and 0.2.x) but was rebuilt around the Kustomize KYAML library (in 0.3.x) to make it more of a generic Kubernetes YAML processor. Like Kustomize, Konjure can act as an aggregator: pulling resource definitions from a number of sources. Konjure is however more limited in what transformations can be applied: the goal being to limit complex interactions between the transformations and aggregation operations. Our primary use case for Konjure here at StormForge is ingesting resource definitions from a variety of sources: some people use Kustomize, some use Helm, others use both. Personally, I also find it a useful timesaver when hacking on scripts.

Please feel free to reach out with any other questions (I'm making sure my watch on this repository gives me notifications now).
